baseURL = 'https://sschonss.github.io/meu-blog/'
languageCode = 'pt-br'
title = 'Luiz Schons'
theme = 'hextra'
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params.navbar]
  displayTitle = true
  displayLogo = false

[params.footer]
  displayCopyright = true
  displayPoweredBy = true

[params.search]
  enable = true
  type = 'flexsearch'

[params.search.flexsearch]
  index = 'content'
  tokenize = 'forward'

[[menu.main]]
  name = 'Artigos'
  pageRef = '/posts'
  weight = 1

[[menu.main]]
  name = 'RSS'
  url = '/meu-blog/index.xml'
  weight = 2

[[menu.main]]
  name = 'Buscar'
  weight = 3
  [menu.main.params]
    type = 'search'
    icon = 'search'

[taxonomies]
  series = 'series'
